In [ ]:
from pathlib import Path
import pandas as pd
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

DATA_DIR = Path('/content/drive/MyDrive/Data/LLM_Climate_Comparison')
CORPORATE_DATA_DIR = DATA_DIR / "corporate_data"
SOURCE_DATA_DIR = CORPORATE_DATA_DIR / "source"
PERSIST_DIR = CORPORATE_DATA_DIR / "persist"

Mounted at /content/drive

# Inspect SBTi data

Data obtained from:
- https://sciencebasedtargets.org/target-dashboard

In [ ]:
companies_file_path = DATA_DIR / "SBTi" / "companies-excel.xlsx"
targets_file_path = DATA_DIR / "SBTi" / "targets-excel.xlsx"

df_companies = pd.read_excel(companies_file_path)
df_targets = pd.read_excel(targets_file_path)

display(df_companies.head())
display(df_targets.head())

,sbti_id,company_name,isin,lei,organization_type,location,region,sector,near_term_status,near_term_target_classification,...,long_term_target_classification,long_term_target_year,net_zero_status,net_zero_year,full_target_language,ba15_status,ba15_date,target_classification_long,reason_for_extension_or_removal,date_updated
0,40009754,AcBel Polytech Inc.,TW0006282007,254900BQVM5V0IY7RQ62,Corporate,"Taiwan, Province of China",Asia,Technology Hardware and Equipment,Targets set,1.5°C,...,NaN,NaN,NaN,NaN,AcBel Polytech Inc commits to reduce absolute ...,NaN,NaT,The targets covering greenhouse gas emissions ...,NaN,2023-06-15 01:00:00
1,40008140,Chalhoub Group,NaN,NaN,Corporate,United Arab Emirates,MENA,Retailing,Targets set,1.5°C,...,1.5°C,2040,Targets set,2040,Overall Net-Zero Target: Chalhoub Group commit...,BA1.5 member,2022-09-15 01:00:00,The targets covering greenhouse gas emissions ...,NaN,2025-05-29 01:00:00
2,40007629,Citrosuco Agroindustria S.A.,NaN,549300YLZY1O51E6VK62,Corporate,Brazil,Latin America and the Caribbean,Food and Beverage Processing,Targets set,Well-below 2°C,...,NaN,NaN,NaN,NaN,Citrosuco SA commits to reduce absolute scopes...,NaN,NaT,The targets covering greenhouse gas emissions ...,NaN,2023-06-15 01:00:00
3,40006454,Cloudfm Group Limited,NaN,NaN,SME,United Kingdom,Europe,Real Estate,Targets set,1.5°C,...,1.5°C,2035,Targets set,2035,This target was approved using a streamlined t...,NaN,NaT,The targets covering greenhouse gas emissions ...,NaN,2023-06-01 01:00:00
4,40014578,Deutsche Glasfaser Group GmbH,NaN,2594009VDKKH30FM3960,Corporate,Germany,Europe,Telecommunication Services,Targets set,1.5°C,...,NaN,NaN,NaN,NaN,Deutsche Glasfaser commits to reduce absolute ...,NaN,NaT,The targets covering greenhouse gas emissions ...,NaN,2023-06-15 01:00:00

,row_entry_id,sbti_id,company_name,isin,lei,location,region,sector,organization_type,validation_route,...,target_wording,scope,target_value,type,sub_type,target_classification_short,base_year,target_year,year_type,date_published
0,18539-40009754,40009754,AcBel Polytech Inc.,TW0006282007,254900BQVM5V0IY7RQ62,"Taiwan, Province of China",Asia,Technology Hardware and Equipment,Corporate,Corporate,...,AcBel Polytech Inc also commits to reduce scop...,3,0.517,Intensity,Reduction,NaN,2021.0,2030.0,CY,2023-06-15 01:00:00
1,07508345-40008140,40008140,Chalhoub Group,NaN,NaN,United Arab Emirates,MENA,Retailing,Corporate,Corporate,...,Chalhoub Group commits to reach net-zero green...,1+2+3,NaN,Net-zero,Other,1.5°C,2021.0,2040.0,CY,2025-05-29 01:00:00
2,24786932-40008140,40008140,Chalhoub Group,NaN,NaN,United Arab Emirates,MENA,Retailing,Corporate,Corporate,...,Chalhoub Group commits to reduce absolute scop...,1+2,0.504,Absolute,Reduction,1.5°C,2021.0,2032.0,CY,2025-05-29 01:00:00
3,19709273-40008140,40008140,Chalhoub Group,NaN,NaN,United Arab Emirates,MENA,Retailing,Corporate,Corporate,...,Chalhoub Group also commits to reduce scope 3 ...,3,0.5814,Intensity,Reduction,NaN,2021.0,2032.0,CY,2025-05-29 01:00:00
4,40987155-40008140,40008140,Chalhoub Group,NaN,NaN,United Arab Emirates,MENA,Retailing,Corporate,Corporate,...,Chalhoub Group commits to reduce absolute scop...,1+2,0.9,Absolute,Reduction,1.5°C,2021.0,2040.0,CY,2025-05-29 01:00:00

In [ ]:
# We only need to use the targets dataframe

sbti_ids = {
    "NVDA": 40018902,
    "MSFT": 40005011,
    "AAPL": 40003329,
    "GOOGL": 40009770,
    "AMZN": 40010768,
    "META": 40011493,
    "TSLA": 40009923,
}

# keep only mag7 companies
df_targets_filtered = df_targets[df_targets["sbti_id"].isin(sbti_ids.values())]
# keep only active targets (absolute or intensity, not renewable energy or supplier engagement targets, nor target commitments)
df_targets_filtered = df_targets_filtered[df_targets_filtered["type"].isin(["Absolute","Intensity"])]
df_targets_filtered.head()

,row_entry_id,sbti_id,company_name,isin,lei,location,region,sector,organization_type,validation_route,...,target_wording,scope,target_value,type,sub_type,target_classification_short,base_year,target_year,year_type,date_published
865,05266586-40009770,40009770,Alphabet Inc.,US02079K1079,5493006MHB84DD0ZWV18,United States of America,Northern America,Software and Services,Corporate,Corporate,...,"Alphabet, Inc. commits to reduce absolute scop...",1+2+3,0.5,Absolute,Reduction,1.5°C,2019.0,2030.0,CY,2025-07-03 01:00:00
1147,13330-40003329,40003329,"Apple, Inc.",US0378331005,HWUPKR0MPOU8FGXBT394,United States of America,Northern America,Technology Hardware and Equipment,Corporate,Corporate,...,"Apple, Inc. commits to reduce absolute combine...",1+2+3,0.62,Absolute,Reduction,1.5°C,2019.0,2030.0,FY,2021-05-06 01:00:00
9240,15778-40005011,40005011,Microsoft Corporation,US5949181045,INR2EJN1ERAN0W5ZP974,United States of America,Northern America,Software and Services,Corporate,Corporate,...,Microsoft also commits to reduce scope 3 GHG e...,3,0.3,Intensity,Reduction,NaN,2017.0,2030.0,CY,2019-09-23 01:00:00
15893,18133-40011493,40011493,"Meta Platforms, Inc.",US30303M1027,BQ4BKCS1HXDV9HN80Z93,United States of America,Northern America,Media,Corporate,Corporate,...,Meta commits to reduce absolute scope 1 and 2 ...,1+2,0.42,Absolute,Reduction,1.5°C,2021.0,2031.0,CY,2024-02-29 01:00:00
30959,85211448-40018902,40018902,NVIDIA,US67066G1040,NaN,United States of America,Northern America,Semiconductors and Semiconductors Equipment,Corporate,Corporate,...,NVIDIA commits to reduce absolute scope 1 and ...,1+2,0.5,Absolute,Reduction,1.5°C,2023.0,2030.0,FY,2025-07-10 01:00:00

In [ ]:
# get a summary
target_summary = (
    df_targets_filtered
      .groupby(["company_name","action","status"], dropna=False)
      .size()
      .reset_index(name="count")
      .sort_values("company_name", ascending=True)
)
target_summary

            company_name  action  status  count
0          Alphabet Inc.  Target     NaN      1
1            Apple, Inc.  Target     NaN      1
2   Meta Platforms, Inc.  Target     NaN      1
3  Microsoft Corporation  Target     NaN      1
4                 NVIDIA  Target     NaN      2

In [ ]:
# individual company detail
company_ticker = "aapl"
df_targets_filtered[df_targets_filtered["sbti_id"].isin([sbti_ids[company_ticker.upper()]])]

,row_entry_id,sbti_id,company_name,isin,lei,location,region,sector,organization_type,validation_route,...,target_wording,scope,target_value,type,sub_type,target_classification_short,base_year,target_year,year_type,date_published
1147,13330-40003329,40003329,"Apple, Inc.",US0378331005,HWUPKR0MPOU8FGXBT394,United States of America,Northern America,Technology Hardware and Equipment,Corporate,Corporate,...,"Apple, Inc. commits to reduce absolute combine...",1+2+3,0.62,Absolute,Reduction,1.5°C,2019.0,2030.0,FY,2021-05-06 01:00:00